#!/bin/bash
#
# =================
#   What uses me?
# =================
#   projects.sh
#   start.sh
#

  dir='/Users/philyoo/webdev'
  ga='/Users/philyoo/wdi'

  case $PROJECT in
    ai)
      ext=/personal/pseudoAI
      START=both
      ;;
    angulartodo)
      ext=/boneyard/angular-todo-app
      START=both
      ;;
    b2dev)
      ext=/b2devs
      START=both
      ;;
    boneyard)
      ext=/boneyard
      ;;
    chad)
      ext=/chad_app
      START=both
      ;;
    chadapp)
      ext=/chad_app
      START=both
      ;;
    cortana)
      ext=/personal/helios/helios-v0.2.0
      START=dev
      ;;
    crm)
      dir=$ga
      ext=/unit02/projects/crm
      START=dev
      ;;
    django-tut)
      ext=/boneyard/django_starter
      ;;
    email)
      ext=/emailwidget
      START=both
      ;;
    eri)
      ext=/ERI-snopes
      START=both
      ;;
    gabot)
      ext=/GABots
      ;;
    gabots)
      ext=/GABots
      ;;
    gastack)
      dir=$ga
      ext=/unit02/projects/stackoverflow
      START=dev
      ;;
    gh)
      ext=/GABots/gracehopper
      ;;
    ghopper)
      ext=/GABots/gracehopper
      ;;
    gracehopper)
      ext=/GABots/gracehopper
      ;;
    helios)
      ext=/personal/helios/helios-v0.2.0
      START=dev
      ;;
    jarvis)
      ext=/personal/helios
      START=dev
      ;;
    mediaviewer)
      ext=/personal/mediaviewer
      ;;
    minesweeper)
      ext=/personal/minesweeper
      ;;
    mustang)
      ext=/GABots/mustangscheduler
      ;;
    mustangbot)
      ext=/GABots/mustangscheduler
      ;;
    octonion)
      ext=/GABots/octonionscheduler
      ;;
    octonionbot)
      ext=/GABots/octonionscheduler
      ;;
    personal)
      ext=/personal/backup_portfolio/client
      START=start
      ;;
    philyoo)
      ext=/personal/backup_portfolio/client
      START=start
      ;;
    pos)
      ext=/pos
      if [[ $AMHOME == 'true' ]]; then
        START=both
      else
        START=all
      fi
      SECONDARY=remote
      ;;
    posclient)
      ext=/pos_clientside
      START=start
      ;;
    psychmeds)
      ext=/psych_meds_app
      START=both
      ;;
    retail)
      ext=/retailpos
      START=start
      ;;
    retailpos)
      ext=/retailpos
      START=start
      ;;
    sandbox)
      ext=/boneyard/sandbox
      ;;
    scripts)
      ext=/scripts
      ;;
    snake)
      dir=$ga
      ext=/unit01/projects/snake
      ;;
    spaceteam)
      dir=$ga
      ext=/unit04/projects/space-team
      START=both
      ;;
    speechtest)
      ext=/boneyard/speech-test
      ;;
    stock)
      ext="/stocks"
      ;;
    stocks)
      ext="/stocks"
      ;;
    templates)
      ext=/templates
      ;;
    tetris)
      dir=$ga
      ext=/unit01/projects/tetris
      ;;
    *)
      echo "$1 does not exist"
  esac

  DIRECTORY=$dir$ext

